# Generated by Django 3.1.5 on 2021-01-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0003_auto_20210113_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='dealer',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='carshowroom.Supplier'),
        ),
    ]
