# Generated by Django 3.1.5 on 2021-01-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0004_auto_20210113_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='adress',
            field=models.CharField(default='', max_length=500),
        ),
    ]
