# Generated by Django 3.1.5 on 2021-01-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshowroom', '0005_supplier_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='price',
            field=models.IntegerField(max_length=100000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='quantity',
            field=models.IntegerField(max_length=1000, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='number',
            field=models.CharField(default=1, max_length=50, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='adress',
            field=models.CharField(default='', max_length=500, verbose_name='Адрес поставщика'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='field',
            field=models.CharField(max_length=500, verbose_name='Поставляемый товар'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название поставщика'),
        ),
    ]
